<?php

namespace App\Validator\Constraint;

use Symfony\Component\Validator\Constraint;

#[\Attribute]
class EntityExists extends Constraint
{

    public string $entity;
    public string $message='Entity {{entity}} with ID {{id}} not exists';

    public function __construct($entity,mixed $options = null, ?array $groups = null, mixed $payload = null)
    {


        parent::__construct($options, $groups, $payload);
        $this->entity = $entity;
    }

    public function validatedBy()
    {
        return EntityExistsValidator::class; // TODO: Change the autogenerated stub
    }

}